# Generated by Django 5.0.2 on 2024-02-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_location_job_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Province',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='state',
            new_name='province',
        ),
    ]
